# Vector Search Configuration
# This file defines which database fields support vector similarity search
# for handling inaccurate or fuzzy user inputs

vector_search_fields:
  # Production order table fields
  - table: "kn_quality_trace_prod_order"
    field: "projectname_s"
    description: "项目名称"
    priority: 1
  - table: "kn_quality_trace_history_fault_info"
    field: "project_name"
    description: "项目名称"
    priority: 1
  - table: "kn_quality_trace_history_fault_ncr"
    field: "project_name"
    description: "项目名称"
    priority: 1
    